name: Build & Deploy testing it tocheck it check it ........to test 
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
     
          script: |
            mkdir test hello 
            cd test 
            git clone https://github.com/shahchandresh2k/ci-cd-to-digitalocean-with-github-actions.git 
            echo 'Deployment successful to digital ocean...helllllloooooooo' 
